name: jepai
description: "Jenius With SenpAI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  firebase_auth: ^5.3.1
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  google_sign_in: ^6.2.1
  introduction_screen: ^3.1.14
  getwidget: ^4.0.0
  audioplayers: ^6.1.0
  flutter_drawing_board: ^0.9.4
  stroke_order_animator: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/ 
    - assets/audio/
    - assets/audio/hiragana/
    - assets/audio/katakana/
    - assets/data/
    - assets/images/splash_logo.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo.png 