// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv1bDbTf0qQTx0jR09sg97wNU9hGEtSwc',
    appId: '1:763253012422:web:6fdd32e8bd63759924e4c7',
    messagingSenderId: '763253012422',
    projectId: 'jepai-project',
    authDomain: 'jepai-project.firebaseapp.com',
    storageBucket: 'jepai-project.appspot.com',
    measurementId: 'G-YH7YE1WKRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPvVmfYG9GQYa1h9kqRVXoJg12oK-bejM',
    appId: '1:763253012422:android:ad668cb9df6a6d7124e4c7',
    messagingSenderId: '763253012422',
    projectId: 'jepai-project',
    storageBucket: 'jepai-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcX-s0uvujzQZMlgiM5joxgjobZThR1qQ',
    appId: '1:763253012422:ios:8adedf3399921d6224e4c7',
    messagingSenderId: '763253012422',
    projectId: 'jepai-project',
    storageBucket: 'jepai-project.appspot.com',
    iosBundleId: 'com.example.jepai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcX-s0uvujzQZMlgiM5joxgjobZThR1qQ',
    appId: '1:763253012422:ios:8a985be6f379988624e4c7',
    messagingSenderId: '763253012422',
    projectId: 'jepai-project',
    storageBucket: 'jepai-project.appspot.com',
    iosBundleId: 'com.jepai.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv1bDbTf0qQTx0jR09sg97wNU9hGEtSwc',
    appId: '1:763253012422:web:42e48e7362d128a524e4c7',
    messagingSenderId: '763253012422',
    projectId: 'jepai-project',
    authDomain: 'jepai-project.firebaseapp.com',
    storageBucket: 'jepai-project.appspot.com',
    measurementId: 'G-RVKCB46NGR',
  );
}
